### ISSUE TITLE
another effing irc client

### ISSUE THREAD

**Issue by ungoldman** [ungoldman/ideas#10]
slack clone for irc with optional persistence via an irc bouncer

maybe add file sharing etc via p2p (direct ip to ip? torrent?)

**Comment by ungoldman** [comment]
(electron + choo project)

**Comment by ungoldman** [comment]
basically I want a better looking desktop irc client that can connect to a persistent irc bouncer with minimal configuration (preferably none) like irccloud

**Comment by bcomnes** [comment]
It would be cool to experiment with append only logs as a mechanism for syncing, and going further back in history from a client to a bouncer.
