### ISSUE TITLE
micro/pico/nano/hypo amp

### ISSUE THREAD

**Issue by ungoldman** [ungoldman/ideas#14]
per discussion w/ @bcomnes today

a minimal version of hyperamp with features we've already achieved:

- load a directory
- play/pause/prev/next
- shuffle
- media key support

but packaged as a taskbar app (no list or other chrome needed).

this would allow us to sign and ship something nice and simple that does most of what we want. plus it would be enough of a basic player for us to work on the distributed/dat/hypercore/? stuff we originally started the hyperamp project to experiment with way back when.

**Comment by bcomnes** [comment]
Maybe we could do it as a separate window with the current codebase, and hide the window we've been working on as a secret mode.  I still want to hack on it at some point but dropping work around features we don't have time / interest for right now will help.

I'm thinking we basically do our current compact mode, more compact with a small list at the bottom, as a task bar app.
